# Configuración de los Screts para el deployment o demás necesario en la App
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # estoEsMiSecretDeK8s en Base64 String - En terminal usar: "echo -n estoEsMiSecretDeK8s | base64"
  JWT_SECRET: ZXN0b0VzTWlTZWNyZXREZUs4cw==