# Configuración de los Screts para el deployment o demás necesario en la App
apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # superman@google.com en Base64 String - En terminal usar: "echo -n superman@google.com | base64"
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # ThisIsASecretePassword en Base64 String - En terminal usar: "echo -n ThisIsASecretePassword | base64"
  DB_PASSWORD: VGhpc0lzQVNlY3JldGVQYXNzd29yZA==