# Configuración de los Screts para el deployment o demás necesario en la App
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= #  ---> postgres en Base64 String
  DB_PASSWORD: VGhpc0lzQVNlY3JldGVQYXNzd29yZA== # ---> ThisIsASecretePassword en Base64 String